### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by loec01** [sebbo2002/fileee-backup-downloader#54]
Hello,
I have fileee-backup-downloader installed but don't want to run it in Docker. But I can't find documentation how to set parameters such as username and password. Can you please let me know?

Thank you
Tobias

i@raspberrypi:~ $ fileee-backup-downloader
 Okay, hi there.
   Let' do some backups!

Error: Unable to run: FILEEE_USERNAME not set.
    at Function.run (/usr/lib/node_modules/@sebbo2002/fileee-backup-downloader/dist/bin/start.cjs:27:19)
    at Object.<anonymous> (/usr/lib/node_modules/@sebbo2002/fileee-backup-downloader/dist/bin/start.cjs:197:24)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

**Comment by sebbo2002** [comment]
These are normal [environment variables](https://en.wikipedia.org/wiki/Environment_variable). If you want to set username/password you can do it like this: 

```
FILEEE_USERNAME=foo FILEEE_PASSWORD=bar fileee-backup-downloader
```
